#makefile in homeworks
all: data_structures control_flow simple_examples functions 
	
simple_examples:
	make -C SimpleExamples/
	
control_flow:

	g++ ControlFlow/if_condition.cpp -o ControlFlow/if_condition.o
	g++ ControlFlow/for_loop.cpp -o ControlFlow/for_loop.o	
	g++ ControlFlow/while_loop.cpp -o ControlFlow/while_loop.o
	g++ ControlFlow/switch_statement.cpp -o ControlFlow/switch_statement.o
	
functions:
	make -C Functions/

data_structures:	
	make -C DataStructures/